### ISSUE TITLE
How to set files to glass theme

### ISSUE THREAD

**Issue by wxnnvs** [iDCoded/Windows-Rice#1]
Hey, i really like your setup, but im wondering how you made/installed that glass theme for files (i assume from https://files.community)

**Comment by dhruvnnd** [comment]
@wxnnvs Hey, sorry for the late response.
To get the same look, set the theme to *Dark Grey* and set the Backdrop to *Thin Acrylic*.

**Comment by wxnnvs** [comment]
Thank you very much!
